In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
page = "https://www.imdb.com/chart/boxoffice/?ref_=nv_ch_cht"
response = requests.get(page)
soup = BeautifulSoup(response.text,'lxml')
print('data is loaded')

data is loaded

In [5]:
target = soup.find('table',attrs={'class':'chart'})
target

<table class="chart full-width" data-caller-name="chart-boxoffice">
<colgroup>
<col class="chartTableColumnPoster"/>
<col class="chartTableColumnTitle"/>
<col class="chartTableGross"/>
<col class="chartTableGross"/>
<col class="chartTableWeeks"/>
<col class="chartTableColumnWatchlistRibbon"/>
</colgroup>
<thead>
<tr>
<th></th>
<th>Title</th>
<th>Weekend</th>
<th>Gross</th>
<th>Weeks</th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td class="posterColumn">
<a href="/title/tt4123432"> <img alt="Fantastic Beasts: The Secrets of Dumbledore" height="67" src="https://m.media-amazon.com/images/M/MV5BZGQ1NjQyNDMtNzFlZS00ZGIzLTliMWUtNGJkMGMzNTBjNDg0XkEyXkFqcGdeQXVyMTE1NDI5MDQx._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt4123432" title="David Yates (dir.), Eddie Redmayne, Jude Law">Fantastic Beasts: The Secrets of Dumbledore</a>
</td>
<td class="ratingColumn">
                            $42.2M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$42.2M</span>
</td>
<td class="weeksColumn">1</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt4123432"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt12412888"> <img alt="Sonic the Hedgehog 2" height="67" src="https://m.media-amazon.com/images/M/MV5BOGM2ZjEzNzQtNzhiNi00ZmFkLTgzZjItZmU4YTZjMTJmNmRhXkEyXkFqcGdeQXVyNDM1ODc2NzE@._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt12412888" title="Jeff Fowler (dir.), James Marsden, Jim Carrey">Sonic the Hedgehog 2</a>
</td>
<td class="ratingColumn">
                            $29.3M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$118.9M</span>
</td>
<td class="weeksColumn">2</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt12412888"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt13320622"> <img alt="The Lost City" height="67" src="https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt13320622" title="Aaron Nee (dir.), Sandra Bullock, Channing Tatum">The Lost City</a>
</td>
<td class="ratingColumn">
                            $6.2M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$78.3M</span>
</td>
<td class="weeksColumn">4</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt13320622"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt6710474"> <img alt="Everything Everywhere All at Once" height="67" src="https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt6710474" title="Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu">Everything Everywhere All at Once</a>
</td>
<td class="ratingColumn">
                            $6.2M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$17.7M</span>
</td>
<td class="weeksColumn">4</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt6710474"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt14439896"> <img alt="Father Stu" height="67" src="https://m.media-amazon.com/images/M/MV5BNGYwOTI1MTUtYmY0Mi00OTAxLTkwNDEtOTI5YTkyZTVhN2JiXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_UY67_CR4,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt14439896" title="Rosalind Ross (dir.), Mark Wahlberg, Mel Gibson">Father Stu</a>
</td>
<td class="ratingColumn">
                            $5.4M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$7.7M</span>
</td>
<td class="weeksColumn">1</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt14439896"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt5108870"> <img alt="Morbius" height="67" src="https://m.media-amazon.com/images/M/MV5BNWExYzEwY2UtZTNhYi00MDRjLTg4YzYtN2QzN2E3MjIwY2Q5XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt5108870" title="Daniel Espinosa (dir.), Jared Leto, Matt Smith">Morbius</a>
</td>
<td class="ratingColumn">
                            $4.7M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$65.1M</span>
</td>
<td class="weeksColumn">3</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt5108870"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt4998632"> <img alt="Ambulance" height="67" src="https://m.media-amazon.com/images/M/MV5BYjUyN2VlZGEtNGEyZC00YjViLTgwYmQtZDJiM2FlOTU3Mjg2XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX45_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt4998632" title="Michael Bay (dir.), Jake Gyllenhaal, Yahya Abdul-Mateen II">Ambulance</a>
</td>
<td class="ratingColumn">
                            $4.1M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$15.7M</span>
</td>
<td class="weeksColumn">2</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt4998632"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt1877830"> <img alt="The Batman" height="67" src="https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt1877830" title="Matt Reeves (dir.), Robert Pattinson, ZoÃ« Kravitz">The Batman</a>
</td>
<td class="ratingColumn">
                            $3.8M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$365.0M</span>
</td>
<td class="weeksColumn">7</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt1877830"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt10698680"> <img alt="K.G.F: Chapter 2" height="67" src="https://m.media-amazon.com/images/M/MV5BMjMwMDgyOGQtMWZjNC00MDUwLTllZDYtZWM3NDBmN2YzNGZmXkEyXkFqcGdeQXVyMTQzNjkzMzEw._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt10698680" title="Prashanth Neel (dir.), Yash, Sanjay Dutt">K.G.F: Chapter 2</a>
</td>
<td class="ratingColumn">
                            $2.9M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$2.9M</span>
</td>
<td class="weeksColumn">1</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt10698680"></div></td>
</tr>
<tr>
<td class="posterColumn">
<a href="/title/tt1464335"> <img alt="Uncharted" height="67" src="https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UY67_CR0,0,45,67_AL_.jpg" width="45"/>
</a> </td><td class="titleColumn">
<a href="/title/tt1464335" title="Ruben Fleischer (dir.), Tom Holland, Mark Wahlberg">Uncharted</a>
</td>
<td class="ratingColumn">
                            $1.2M
                    </td>
<td class="ratingColumn">
<span class="secondaryInfo">$145.0M</span>
</td>
<td class="weeksColumn">9</td>
<td class="watchlistColumn"><div class="wlb_ribbon" data-tconst="tt1464335"></div></td>
</tr>
</tbody>
</table>

In [9]:
target = soup.find('table',attrs={'class':'chart'}).tbody

In [10]:
rows = target.find_all('tr')
len(rows)

10

In [14]:
movies = []
for row in rows:
    title = row.find('td',attrs= {'class':'titleColumn'})
    weekend = row.find('td',attrs= {'class':'ratingColumn'})
    gross = row.find_all('td',attrs= {'class':'ratingColumn'})[-1]
    week = row.find('td',attrs= {'class':'weeksColumn'})
    print(title.text.strip())
    print(weekend.text.strip()) 
    print(gross.text.strip())
    print(week.text.strip())

Fantastic Beasts: The Secrets of Dumbledore
$42.2M
$42.2M
1
Sonic the Hedgehog 2
$29.3M
$118.9M
2
The Lost City
$6.2M
$78.3M
4
Everything Everywhere All at Once
$6.2M
$17.7M
4
Father Stu
$5.4M
$7.7M
1
Morbius
$4.7M
$65.1M
3
Ambulance
$4.1M
$15.7M
2
The Batman
$3.8M
$365.0M
7
K.G.F: Chapter 2
$2.9M
$2.9M
1
Uncharted
$1.2M
$145.0M
9

In [23]:
movies = []
for row in rows:
    title = row.find('td',attrs= {'class':'titleColumn'})
    weekend = row.find('td',attrs= {'class':'ratingColumn'})
    gross = row.find_all('td',attrs= {'class':'ratingColumn'})[-1]
    week = row.find('td',attrs= {'class':'weeksColumn'})
    movies.append({
    'title':title.text.strip(),
    'weekend':weekend.text.strip(),
    'gross':gross.text.strip(),
    'week':week.text.strip()

    })
data = pd.DataFrame(movies)
data

                                         title weekend    gross week
0  Fantastic Beasts: The Secrets of Dumbledore  $42.2M   $42.2M    1
1                         Sonic the Hedgehog 2  $29.3M  $118.9M    2
2                                The Lost City   $6.2M   $78.3M    4
3            Everything Everywhere All at Once   $6.2M   $17.7M    4
4                                   Father Stu   $5.4M    $7.7M    1
5                                      Morbius   $4.7M   $65.1M    3
6                                    Ambulance   $4.1M   $15.7M    2
7                                   The Batman   $3.8M  $365.0M    7
8                             K.G.F: Chapter 2   $2.9M    $2.9M    1
9                                    Uncharted   $1.2M  $145.0M    9

In [22]:
data.to_csv('boxoffice.csv',index = False)